#include "Palettes.h"

#include "Palettes/RougePalette16.dat"
#include "Palettes/NoirPalette16.dat"
#include "Palettes/RetourneePalette16.dat"
#include "Palettes/CurseurPalette16.dat"
#include "Palettes/MainGameTilesPalette256.dat"
#include "Palettes/IntroPicPalette256.dat"
#include "Palettes/IntroZeroPicPalette256.dat"
#include "Palettes/SHOOTPalette16.dat"
#include "Palettes/DAPalette16.dat"
#include "Palettes/MOONPalette16.dat"
#include "Palettes/SpherePalette256.dat"
#include "Palettes/GameMenuPalette256.dat"
#include "Palettes/SplashScreenPalette256.dat"
